export default {
    GET_USER_BY_EMAIL: 'get_user_by_email',
    GET_USER_BY_ID: 'get_user_by_id',
    GET_USER_BY_GOOGLE_ID: 'get_user_by_google_id',
    GET_CATEGORIES_BY_PARENT_ID: 'get_category_by_parent_id',
    GET_ROOT_CATEGORIES: 'get_root_categories',
    GET_DISH: 'get_dish',
    GET_DISHES_BY_CATEGORY_ID: 'get_dishes_by_category_id',
    GET_DISHES_FROM_CART: 'get_dishes_from_cart',
    GET_DISH_FROM_CART: 'get_dish_from_cart',
    GET_USER_RESERVATION: 'get_user_reservation',
    GET_USER_RESERVATIONS: 'get_user_reservations',
    GET_DISHES_FROM_WISH_LIST: 'get_dishes_from_wish_list',
    GET_DISH_FROM_WISH_LIST: 'get_dish_from_wish_list',
}
